version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
      args:
        GOOGLE_ANALYTICS: "UA-136777636-1"
        WEB_SERVICE_USER: ${WEB_SERVICE_USER}
        WEB_SERVICE_PASSWORD: ${WEB_SERVICE_PASSWORD}
    depends_on:
      - web-server
    restart: unless-stopped
    ports:
      - "8020:80"
  rabbitmq:
    build:
      context: ./
      dockerfile: ./rabbitmq/Dockerfile
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
  flower:
    build: https://github.com/mher/flower.git
    command: "celery flower --url_prefix=service/flower"
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
    depends_on:
      - rabbitmq
  web-server:
    build:
      context: ./
      dockerfile: ./web-server/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
      PRANKWEB_DATA: "/data/prankweb"
    restart: unless-stopped
    volumes:
      - predictions:/data/prankweb
  executor:
    build:
      context: ./
      dockerfile: ./executor/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
    restart: unless-stopped
    volumes:
      - conservation:/data/conservation
      - predictions:/data/prankweb
  monitor:
    build:
      context: ./
      dockerfile: ./monitor/Dockerfile
    environment:
      GOOGLE_ANALYTICS: "UA-136777636-2"
    restart: unless-stopped
volumes:
  conservation:
    external: True
    name: prankweb_conservation
  predictions:
    external: True
    name: prankweb_predictions
  rabbitmq:
    external: True
    name: prankweb_rabbitmq
